"""empty message

Revision ID: 407089126206
Revises: fbd048ae0c5c
Create Date: 2023-05-20 16:15:34.141332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407089126206'
down_revision = 'fbd048ae0c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
