"""completed users

Revision ID: 5d97e715cd45
Revises: 
Create Date: 2023-04-10 19:43:55.858478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d97e715cd45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qty_donations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_last_donation', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('date_last_donation')
        batch_op.drop_column('qty_donations')
        batch_op.drop_column('sex')
        batch_op.drop_column('phone')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
