"""empty message

Revision ID: 0e4d9dde1afa
Revises: 30e267855624
Create Date: 2023-11-05 20:18:28.013251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4d9dde1afa'
down_revision = '30e267855624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_order', schema=None) as batch_op:
        batch_op.alter_column('blood_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_order', schema=None) as batch_op:
        batch_op.alter_column('blood_type',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
